### ISSUE TITLE
UI image may not be necessary to live here 

### ISSUE THREAD

**Issue by sophtron-jishun** [Universal-Connect-Project/ucw-app#31]
Looking at this new repo. I go the idea of using `docker-compose up` to achieve a one click start-up
although this still assumes 2 image built and available from dockerhub

giving that said. the UI image can be built any where, doesn't have to be from this repo. we can simply move the app shell and docker file back into the UI repo and build image from there, this makes no difference to docker, 

in that case we can remove the need of having a npm package , for the reasons I think:

- if we are debugging the UI from the UI repo. we'll have to create a test app shell to load the UI because it's not a complete website but a react component,  this will become no problem if it's not just a npm component but a full site ready to go into docker
- using a npm package prevents others from making their own custom build. I know this won't likely happen in the near future but it's an opensource project designed to be customised by clients,  if a client wants to folk and cusotmize in this pattern, they'll have to publish their customisations into another npm package, 
- this package is big heavy and does only one specific thing, loggically it's a stand-along service,  not a shareable library hence we get no benefit from a npm package other than just shipping the code, while providing the Dockerfile for building a image serves this purpose well enough

**Comment by sophtron-jishun** [comment]
any progress on this one ? 
building ui changes is blocked by this issue for having to have a npm package

**Comment by tphalp** [comment]
When we discussed these changes a couple of months ago, one reason for having the NPM package was that other companies can use the widget in their own implementations. 

MX plans to use the UCW NPM package for their widget in the coming months. 

Right now, if a company wants to make changes, they can either submit a PR or fork the `universal-connect-widget-new` (which will eventually be renamed to make its purpose more clear), which is where the widget code lives (and is also used to publish updates to the NPM package for the widget).

If there are other scenarios that this use-case doesn't address, let's please discuss them. 

We are also working on a GH action that will auto-publish the NPM package when changes are committed to `main`, which will make the process much more streamlined. We are also working on GH actions that will do this with the docker images that come from the `ucw-app` repo.

**Comment by sophtron-jishun** [comment]
Yeah I do remember when we discussed about making an npm package for the widget, I agree with this part,  this is not what I mean by this issue

I think we can have an NPM package, this is going to make things much easier for clients who wants to embeded the widget in their app code directly , as you said

however I don't think we should force only to have an NPM package. the more generic use case is that client to host the widget by using a docker image. the Docker file in this repo for building UI does nothing but to pull the npm package,  this creates an unnecessary dependency.  while the Docker file could have built the image by using the code directly.  

one purpose of having it opensource is to make things more convenient.  clients can make customizations that's not suitable to stay here in the public repo. for example. changing the texts into their own wording or naming.  or adding their own authentication handling, what they can do is to simply clone the github source, apply a patch and build a image. so long as they have a Dockerfile ready.   having a dockerfile doesn't stop you from publishing a npm package either. 

particularly in this current code, of course it's unable to build the code directly because the code isn't here, while that should not be a problem. the point is, the DockerFile should simple stay with the ui code, it doesn't affect anything in this repo. because docker-compose doesn't care where the docker file is

**Comment by tphalp** [comment]
You bring up some really good points. We should discuss how to make customization easier. We've discussed it some here, among the MX team members, and it seems there are still some ways to make this project easier to use and customize.

**Comment by tphalp** [comment]
Hi, @sophtron-jishun. Sorry for the delay in continuing this discussion. 

I talked with the team at MX, and because MX is ultimately going to rely on the widget project (meaning, the NPM package/repo), and they are going to be relying on the widget-only codebase (again, the NPM package), we don't want to include the widget-only code within another repo. That would not allow companies such as MX to consume only the widget (NPM package). 

Due to this restriction, we don't feel like it's possible to do what you are suggesting. 

To be clear, anyone can still develop and customize the widget without publishing changes to NPM for the widget. 

They would just need to clone the `ucw-app` repo, and the `universal-connect-widget-new` repo (name will eventually be changed to make it more clear as to what the repo contains). 

They can then:

- Link the NPM widget repo (`universal-connect-widget-new`) to the `ucw-app` repo (see [this readme](https://github.com/Universal-Connect-Project/universal-connect-widget-new/blob/main/README.md) for details on how to do this)
- Run the `ucw-app` `server` app in dev mode, with `npm run server`.

This should allow a fairly straightforward development experience for making customizations.

**Comment by tphalp** [comment]
One other thing I should mention....we now have auto-publishing enabled for the npm package (when PRs are merged on `universal-connect-widget-new`), and the docker images (when PRs are merged from `ucw-app`), so changes to the widget and app (server/ui) will be published as soon as a PR with the changes are approved.

**Comment by sophtron-jishun** [comment]
@tphalp thanks for the explanation. yeah I understand there are ways to work with NPM packages,  and yes with auto publishing in place, making build is unblocked 

about the npm link stuff,   it's well enough for local development.  but how about making a customised production build? I think this can still work, either npm link or copy the folders and npm install the folder, but it's just not feeling so right for a production build with utilizing these dev tools designed for local development, besides it's some additional steps to take. 

I know that MX uses relies on the NPM package, but what I'm trying to say is, if the a docker file and the minimal app wrapper is also available with the npm code, it doesn't stop publishing an NPM package. but only makes the docker image easier. 

thank you for the update, at least making new official build with the auto published package should work now.
